'use client'

import { useState, useEffect } from 'react'

import { Button } from '@/components/ui/button'
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select'
import { useToast } from '@/lib/hooks/use-toast'

interface Branch {
  id: string
  name: string
  code: string | null
}

// Default window: last 30 days. Mirrors the API's own fallback so a fresh
// visit has data to export without configuration.
function defaultRange(): { startDate: string; endDate: string } {
  const end = new Date()
  const start = new Date(end.getTime() - 30 * 24 * 60 * 60 * 1000)
  const iso = (d: Date) => d.toISOString().slice(0, 10)
  return { startDate: iso(start), endDate: iso(end) }
}

function toIsoWithOffset(yyyyMmDd: string, endOfDay = false): string {
  // Convert YYYY-MM-DD to a full ISO string with timezone offset so the
  // z.string().datetime({ offset: true }) schema in the API accepts it.
  const d = new Date(`${yyyyMmDd}T00:00:00`)
  if (endOfDay) d.setHours(23, 59, 59, 999)
  return d.toISOString()
}

export default function Form35Page() {
  const toast = useToast()
  const [branches, setBranches] = useState<Branch[]>([])
  const [branchId, setBranchId] = useState<string>('')
  const [loadingBranches, setLoadingBranches] = useState(true)
  const [branchError, setBranchError] = useState<string | null>(null)
  const [{ startDate, endDate }, setRange] = useState(defaultRange)
  const [downloading, setDownloading] = useState(false)

  useEffect(() => {
    fetch('/api/inventory/branches')
      .then((res) => res.json())
      .then((body) => {
        const list = (body?.data ?? []) as Branch[]
        if (list.length === 0) {
          setBranchError('No branches available for the current user.')
        } else {
          setBranches(list)
          setBranchId(list[0].id)
        }
      })
      .catch(() => setBranchError('Failed to load branch list.'))
      .finally(() => setLoadingBranches(false))
  }, [])

  async function handleDownload() {
    if (!branchId) {
      toast.error('Select a branch first.')
      return
    }
    if (!startDate || !endDate) {
      toast.error('Pick both start and end dates.')
      return
    }
    if (new Date(startDate) > new Date(endDate)) {
      toast.error('Start date must be before end date.')
      return
    }

    setDownloading(true)
    try {
      const params = new URLSearchParams({
        branchId,
        startDate: toIsoWithOffset(startDate, false),
        endDate: toIsoWithOffset(endDate, true),
      })
      const res = await fetch(`/api/compliance/form35?${params.toString()}`)
      if (!res.ok) {
        const json = (await res.json().catch(() => null)) as {
          error?: { message?: string }
        } | null
        if (res.status === 401) {
          toast.error('Session expired. Please sign in again.')
        } else if (res.status === 403) {
          toast.error(json?.error?.message ?? 'You do not have access to this report.')
        } else if (res.status === 400) {
          toast.error(json?.error?.message ?? 'Invalid date range.')
        } else {
          toast.error(json?.error?.message ?? 'Failed to generate Form 35 PDF.')
        }
        return
      }

      // Pull filename out of Content-Disposition if the server set one.
      const disposition = res.headers.get('Content-Disposition') ?? ''
      const match = /filename="?([^"]+)"?/.exec(disposition)
      const filename = match?.[1] ?? 'form-35-register.pdf'

      const blob = await res.blob()
      const url = window.URL.createObjectURL(blob)
      const link = document.createElement('a')
      link.href = url
      link.download = filename
      document.body.appendChild(link)
      link.click()
      document.body.removeChild(link)
      window.URL.revokeObjectURL(url)
      toast.success('Form 35 PDF downloaded')
    } catch {
      toast.error('Failed to generate Form 35 PDF.')
    } finally {
      setDownloading(false)
    }
  }

  return (
    <div className="space-y-4">
      <div>
        <h1 className="text-2xl font-bold tracking-tight">Form 35 — Schedule H1 Register</h1>
        <p className="text-muted-foreground">
          Branch-scoped PDF export for the controlled-substance register.
        </p>
      </div>

      <Card>
        <CardHeader>
          <CardTitle>Generate PDF</CardTitle>
          <CardDescription>
            Choose the branch and reporting window. The PDF is generated by{' '}
            <code className="font-mono text-xs">GET /api/compliance/form35</code> and downloaded to
            your device.
          </CardDescription>
        </CardHeader>
        <CardContent className="space-y-4">
          <div className="grid gap-4 sm:grid-cols-3">
            <div className="space-y-1">
              <Label>Branch</Label>
              {loadingBranches ? (
                <p className="text-sm text-muted-foreground">Loading branches…</p>
              ) : branchError ? (
                <p className="text-sm text-destructive">{branchError}</p>
              ) : (
                <Select value={branchId} onValueChange={setBranchId}>
                  <SelectTrigger>
                    <SelectValue placeholder="Select branch" />
                  </SelectTrigger>
                  <SelectContent>
                    {branches.map((b) => (
                      <SelectItem key={b.id} value={b.id}>
                        {b.name}
                      </SelectItem>
                    ))}
                  </SelectContent>
                </Select>
              )}
            </div>
            <div className="space-y-1">
              <Label htmlFor="form35-start">Start date</Label>
              <Input
                id="form35-start"
                type="date"
                value={startDate}
                max={endDate}
                onChange={(e) => setRange((r) => ({ ...r, startDate: e.target.value }))}
              />
            </div>
            <div className="space-y-1">
              <Label htmlFor="form35-end">End date</Label>
              <Input
                id="form35-end"
                type="date"
                value={endDate}
                min={startDate}
                max={defaultRange().endDate}
                onChange={(e) => setRange((r) => ({ ...r, endDate: e.target.value }))}
              />
            </div>
          </div>

          <div className="flex flex-wrap items-center justify-between gap-2">
            <p className="text-xs text-muted-foreground">
              Default window is the last 30 days. Requires <code>reports:export</code>.
            </p>
            <Button
              type="button"
              onClick={handleDownload}
              disabled={downloading || loadingBranches || !!branchError || !branchId}
            >
              {downloading ? 'Generating…' : 'Download Form 35 PDF'}
            </Button>
          </div>
        </CardContent>
      </Card>
    </div>
  )
}
