'use strict'

const { classDefs } = require('../lib/mermaid')

/**
 * Graphify — Authentication & Authorization Flow.
 *
 * How users log in, how sessions are created, how middleware gates routes,
 * and how RBAC (role + permission) authorization works at both the page and
 * API route levels. All policies, lockout thresholds and seeded role /
 * permission names come from the actual implementation.
 */

module.exports = function buildAuthFlow(ctx) {
  const lines = [
    'flowchart TB',
    classDefs({
      ui: 'fill:#f0fdf4,stroke:#16a34a,color:#14532d',
      auth: 'fill:#fff7ed,stroke:#ea580c,color:#7c2d12',
      mw: 'fill:#fef2f2,stroke:#dc2626,color:#7f1d1d',
      data: 'fill:#fdf4ff,stroke:#a21caf,color:#701a75',
      page: 'fill:#eff6ff,stroke:#2563eb,color:#1e3a8a',
      note: 'fill:#f8fafc,stroke:#94a3b8,color:#334155',
    }),
    '',
    'subgraph UI["1 · Login page (Client)"]',
    '  U1["LoginForm component — email + password inputs"]:::ui',
    '  U2["React form validation (Zod)"]:::ui',
    '  U3["POST to /api/auth/csrf then signIn(\'credentials\', ...)"]:::ui',
    'end',
    '',
    'subgraph AUTH["2 · NextAuth Credentials provider (Server)"]',
    '  A1["/api/auth/[…nextauth]/route.ts — auth-config.ts"]:::auth',
    '  A2["authorize({email, password})"]:::auth',
    '  A3{"User found?"}:::auth',
    '  A4{"isActive?"}:::auth',
    '  A5{"Account locked?\\n(lockedUntil > now)"}:::auth',
    '  A6{"Password valid?\\nbcrypt.compare"}:::auth',
    '  A7["OK → reset failedLoginCount · set lastLoginAt"]:::auth',
    '  A8["FAIL → increment failedLoginCount\\nlock for 15 min if count ≥ 4\\n(coalesced: locks on 5th failure)"]:::auth',
    '  A9["Return JWT-safe payload\\n{id, name, email, image, permissions[], roles[], branchId}"]:::auth',
    'end',
    '',
    'subgraph JWT["3 · Session (JWT strategy, 30-day maxAge)"]',
    '  J1["jwt() callback — embeds id · permissions · roles · branchId on token"]:::auth',
    '  J2["session() callback — copies to session.user.*"]:::auth',
    '  J3["Prisma adapter linked (accounts, sessions tables exist) but strategy = JWT"]:::auth',
    'end',
    '',
    'subgraph MW["4 · Middleware (every protected route)"]',
    '  M1["src/middleware.ts — NextAuth withAuth()"]:::mw',
    '  M2{"token present?"}:::mw',
    '  M3{"pathname starts with /pos ?"}:::mw',
    '  M4{"token.permissions includes sales:create?"}:::mw',
    '  M5["next()"]:::mw',
    '  M6["redirect → /login"]:::mw',
    '  M7["redirect → / (deny POS access)"]:::mw',
    'end',
    '',
    'subgraph SERVER["5 · Server Components + API routes"]',
    '  S1["Dashboard layout — getServerSession(authOptions)"]:::page',
    '  S2{"session exists?"}:::page',
    '  S3["redirect(/login)"]:::page',
    '  S4["can(permission) / requirePermission(perm)"]:::page',
    '  S5["API routes — requirePermission() throws 403 if denied"]:::page',
    'end',
    '',
    'subgraph PERM["6 · RBAC model (seeded)"]',
    '  P1["6 roles: owner · manager · pharmacist · cashier · purchase_manager · accountant"]:::data',
    '  P2["60 permissions across 15 modules (users:*, products:*, sales:*, batches:*, inventory:*, ..."]:::data',
    '  P3["RolePermission join table → role.rolePermissions[].permission.code"]:::data',
    '  P4["UserRole join table → user.userRoles[].role.name"]:::data',
    '  P5["Session.user.permissions = flattened unique codes across all roles"]:::data',
    'end',
    '',
    'subgraph LOGOUT["7 · Sign out"]',
    '  L1["next-auth/signOut({callbackUrl: /login})"]:::ui',
    '  L2["auth-config events.signOut — writes AuditLog {action: LOGOUT, entity: User}"]:::data',
    'end',
    '',
    'U1 --> U2 --> U3',
    'U3 --> A1',
    'A1 --> A2',
    'A2 --> A3',
    'A3 -->|No| A8',
    'A4 -->|No| A8',
    'A5 -->|Locked| A8',
    'A6 -->|No| A8',
    'A7 --> A9',
    'A3 -->|Yes| A4',
    'A4 -->|Yes| A5',
    'A5 -->|No| A6',
    'A9 --> J1',
    'J1 --> J2',
    'J1 --> J3',
    'J2 --> M1',
    'M1 --> M2',
    'M2 -->|No| M6',
    'M2 -->|Yes| M3',
    'M3 -->|Yes| M4',
    'M4 -->|Yes| M5',
    'M4 -->|No| M7',
    'M3 -->|No| M5',
    'M5 --> S1',
    'S1 --> S2',
    'S2 -->|No| S3',
    'S2 -->|Yes| S4',
    'S4 --> S5',
    'P1 --> P3',
    'P2 --> P3',
    'P3 --> P5',
    'P4 --> P5',
    'L1 --> L2',
  ]

  return {
    id: 'auth-flow',
    title: 'Authentication & Authorization Flow',
    group: 'Security',
    groupOrder: 4,
    accent: '#ea580c',
    description:
      'How users log in, how sessions are created, how middleware gates routes, and how RBAC (role + permission) authorization works at both the page and API route levels. All policies, lockout thresholds and seeded role/permission names are from the actual implementation.',
    sourceFiles: [
      'src/lib/auth/auth-config.ts',
      'src/lib/auth/auth-helpers.ts',
      'src/middleware.ts',
      'src/app/(auth)/login/page.tsx',
      'src/components/auth/login-form.tsx',
      'src/app/(dashboard)/layout.tsx',
      'src/lib/constants/roles.ts',
      'src/lib/constants/permissions.ts',
      'prisma/seeds/roles.ts',
      'prisma/seeds/permissions.ts',
    ],
    mermaid: lines.join('\n'),
  }
}