'use strict'

/**
 * Graphify — PharmaCare architecture visualiser (main entry).
 *
 * Generates focused, locally-viewable architecture graphs from the REAL
 * PharmaCare codebase:
 *
 *   - prisma/schema.prisma   → database overview + domain ERDs
 *   - src/**                 → system architecture, module map, auth/sales
 *                              flows, reporting flow, testing architecture
 *
 * Output (under documentation/graphify/):
 *   - graphs/*.md            → mermaid markdown
 *   - viewer.html            → single-file offline viewer
 *   - assets/mermaid.min.js  → copied from node_modules for offline viewing
 *   - README.md              → how-to guide
 */

const fs = require('fs')
const path = require('path')

const SCRIPT_DIR = __dirname
const PROJECT_ROOT = path.resolve(SCRIPT_DIR, '..', '..')

// ---------------------------------------------------------------------------
// Wiring
// ---------------------------------------------------------------------------

function loadContext() {
  const root = PROJECT_ROOT

  const schemaParser = require(path.join(SCRIPT_DIR, 'lib', 'prisma-schema-parser.js'))
  const scanner = require(path.join(SCRIPT_DIR, 'lib', 'source-scanner.js'))

  const schema = schemaParser.parseSchema(path.join(root, 'prisma', 'schema.prisma'))
  const src = scanner.scan(path.join(root, 'src'), path.join(root, 'e2e'))

  return {
    projectRoot: root,
    schema,
    src,
  }
}

function buildGraphs(ctx) {
  const builders = [
    require('./graphs/system-architecture.js'),
    require('./graphs/module-map.js'),
    require('./graphs/database.js'),
    require('./graphs/auth-flow.js'),
    require('./graphs/sales-flow.js'),
    require('./graphs/purchase-flow.js'),
    require('./graphs/reporting-flow.js'),
    require('./graphs/testing-architecture.js'),
  ]

  const graphs = []
  for (const build of builders) {
    const result = build(ctx)
    if (Array.isArray(result)) graphs.push(...result)
    else graphs.push(result)
  }
  return graphs
}

// ---------------------------------------------------------------------------
// Markdown documents
// ---------------------------------------------------------------------------

function mdHeader(graph) {
  const generated = new Date().toISOString().slice(0, 10)
  const lines = []
  lines.push('# ' + graph.title)
  lines.push('')
  lines.push(
    '> Auto-generated by `scripts/graphify` on ' + generated + ' from the actual repository files. Do not edit by hand — run `npm run graphify` to regenerate.'
  )
  lines.push('')
  lines.push('## Diagram')
  lines.push('')
  lines.push('```mermaid')
  lines.push(graph.mermaid)
  lines.push('```')
  lines.push('')
  lines.push('## What this graph represents')
  lines.push('')
  lines.push(graph.description || '')
  lines.push('')
  lines.push('## Source files')
  lines.push('')
  for (const f of graph.sourceFiles || []) {
    lines.push('- `' + f + '`')
  }
  lines.push('')
  lines.push('_See [../README.md](../README.md) for how to view and regenerate._')
  lines.push('')
  return lines.join('\n')
}

function writeMarkdown(graphs, outDir) {
  const dir = path.join(outDir, 'graphs')
  fs.mkdirSync(dir, { recursive: true })
  for (const graph of graphs) {
    const full = graph._fullMarkdown || mdHeader(graph)
    const file = path.join(dir, graph.id + '.md')
    fs.writeFileSync(file, full, 'utf8')
    graph.file = path.relative(outDir, file).split(path.sep).join('/')
  }
}

// ---------------------------------------------------------------------------
// Viewer
// ---------------------------------------------------------------------------

function writeViewer(graphs, outDir) {
  const render = require('./lib/render.js')
  render.writeViewer(graphs, outDir)

  const pkgMermaid = path.join(PROJECT_ROOT, 'node_modules', 'mermaid', 'dist', 'mermaid.min.js')
  const assetsDir = path.join(outDir, 'assets')
  fs.mkdirSync(assetsDir, { recursive: true })
  if (fs.existsSync(pkgMermaid)) {
    fs.copyFileSync(pkgMermaid, path.join(assetsDir, 'mermaid.min.js'))
    return true
  }
  return false
}

// ---------------------------------------------------------------------------
// README
// ---------------------------------------------------------------------------

function writeReadme(graphs, outDir, viewerOk) {
  const render = require('./lib/render.js')
  render.writeReadme(graphs, outDir, viewerOk, PROJECT_ROOT)
}

// ---------------------------------------------------------------------------
// Regenerate & report
// ---------------------------------------------------------------------------

function regenerate(opts) {
  opts = opts || {}
  const ctx = loadContext()
  const graphs = buildGraphs(ctx)

  const outDir = path.join(PROJECT_ROOT, 'documentation', 'graphify')
  fs.mkdirSync(outDir, { recursive: true })

  writeMarkdown(graphs, outDir)
  const viewerOk = writeViewer(graphs, outDir)
  writeReadme(graphs, outDir, viewerOk)

  if (!opts.quiet) {
    printReport(ctx, graphs, outDir, viewerOk)
  }

  return { ctx, graphs, outDir, viewerOk }
}

function printReport(ctx, graphs, outDir, viewerOk) {
  console.log('')
  console.log('Graphify — PharmaCare architecture visualisation')
  console.log('===============================================')
  console.log('')
  console.log(
    'Schema : ' + ctx.schema.stats.modelCount + ' models, ' +
    ctx.schema.stats.enumCount + ' enums, ' +
    ctx.schema.stats.relationCount + ' FK relations'
  )
  const kinds = {}
  for (const f of ctx.src.files) kinds[f.kind] = (kinds[f.kind] || 0) + 1
  console.log(
    'Source : ' +
      Object.keys(kinds).map((k) => `${k} (${kinds[k]})`).join(', ')
  )
  console.log(
    'Stubs  : ' + ctx.src.placeholders.length + ' placeholder pages detected ("Coming in Phase N")'
  )
  console.log('')
  console.log('Generated:')
  for (const g of graphs) {
    console.log(`   - ${g.title.padEnd(56)} ${g.file}`)
  }
  console.log('')
  console.log(
    `Viewer : ${path.join('documentation', 'graphify', 'viewer.html')}${viewerOk ? ' (mermaid bundled, offline-ready)' : ' (WARNING: mermaid.min.js not found)'}`
  )
  console.log('')
  console.log('Tip: open documentation/graphify/viewer.html in any browser, or run npm run graphify:view.')
}

// ---------------------------------------------------------------------------
// Watch mode
// ---------------------------------------------------------------------------

function watchMode() {
  const schemas = [path.join(PROJECT_ROOT, 'prisma', 'schema.prisma')]
  const srcRoot = path.join(PROJECT_ROOT, 'src')
  const e2eRoot = path.join(PROJECT_ROOT, 'e2e')
  const configs = ['package.json', 'playwright.config.ts', 'jest.config.ts']
    .map((p) => path.join(PROJECT_ROOT, p))

  function collect(dir, acc = []) {
    if (!fs.existsSync(dir)) return acc
    for (const e of fs.readdirSync(dir, { withFileTypes: true })) {
      if (e.name === 'node_modules') continue
      const full = path.join(dir, e.name)
      if (e.isDirectory()) collect(full, acc)
      else if (/\.(ts|tsx|js|mjs|prisma)$/.test(e.name)) acc.push(full)
    }
    return acc
  }

  const watched = [...configs, ...collect(srcRoot), ...collect(e2eRoot)]
  const mtimes = new Map()
  for (const f of watched) {
    try { mtimes.set(f, fs.statSync(f).mtimeMs) } catch (e) { /* ignore */ }
  }

  let timer = null
  function check() {
    let changed = false
    for (const f of watched) {
      try {
        const m = fs.statSync(f).mtimeMs
        if (m && mtimes.get(f) !== m) { mtimes.set(f, m); changed = true }
      } catch (e) { /* ignore */ }
    }
    if (changed && !timer) {
      timer = setTimeout(() => {
        timer = null
        try { regenerate({ quiet: false }); console.log('[graphify] regenerated', new Date().toLocaleTimeString()) }
        catch (err) { console.error('[graphify] regeneration failed:', err.message) }
      }, 400)
    }
  }

  console.log('Graphify — watch mode. Regenerates on changes to prisma/schema.prisma, src/** or configs.')
  console.log('Press Ctrl+C to stop.')
  regenerate({ quiet: true })
  setInterval(check, 1000)
}

// ---------------------------------------------------------------------------
// Exports + Entry
// ---------------------------------------------------------------------------

module.exports = { regenerate }

if (require.main === module) {
  if (process.argv.includes('--watch')) {
    watchMode()
  } else {
    regenerate({ quiet: false })
  }
}